### ISSUE TITLE
install failure when upgraded dbt to 1.0

### ISSUE THREAD

**Issue by Brentgreenwood** [tuanchris/dbt-generator#4]
Issue:
After upgrading my local dbt core install to 1.0, attempting to install the previous version of dbt-generator was failing.  Errors pointed to the requirements.txt and attempting to list package metadata. Noticed the requirements.txt had the older style naming for dbt, and was suspicious of version conflict given the install changes with dbt 1.0.

Potential resolution:
Updated my fork's requirements.txt to the newer dbt1.0 naming (removed "dbt" and added dbt-snowflake and dbt-bigquery based on the code and tests I'm seeing in the project here).  With that change, local install via pip from my fork is successful.

This requirements change also appears to be backwards compatible.  With the change, I was able to successfully install and run dbt-generator generate on dbt 1.0 and dbt 0.21.

Can send the change over in a PR if you'd like.  But wanted to ask first if you'd like to test more thoroughly if you have installs with older dbt versions.

**Comment by GJMcClintock** [comment]
thanks for this @Brentgreenwood  - installing from your branch worked for me as well.

**Comment by tuanchris** [comment]
Sorry, guys. Merged your PR. Thank you @Brentgreenwood
